name: CI
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Copy config template
      run: cp config.template.android.json config.json
    - name: Lint code
      run: npm run lint
  unittest:
    name: Unittest
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Copy config template
      run: cp config.template.android.json config.json
    - name: Run tests
      run: npm run unittest
